spring:
  security:
    user:
      name: nimo
      password: 123
      roles: ADMIN,USER
  datasource:
    url: jdbc:mysql://localhost:3306/security_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456