server:
  port: 8080

spring:
  application:
    name: springboot-tabbitmq
  rabbitmq:
    host: 192.168.0.88
    port: 5672
    username: mqtt_test
    password: 1234Qwermq
    listener:
      direct:
        # 开启手动确认机制
        acknowledge-mode: manual
    # 开启消息确认机制
    publisher-confirm-type: correlated
    # 开启回退消息
    publisher-returns: true