server:
  port: 8080

spring:
  application:
    name: springboot-tabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        # 开启手动确认机制
        acknowledge-mode: manual
    # 开启消息确认机制
    publisher-confirm-type: correlated
    # 开启回退消息
    publisher-returns: true