server:
  port: 8080

spring:
  application:
    name: springboot-tabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        # 开启手动确认机制
        acknowledge-mode: manual